ARG PYTHON_VERSION=3.8
FROM python:${PYTHON_VERSION} as baseimage

ARG WORKDIR=/usr/src/app
WORKDIR $WORKDIR

ARG PYTHONUSERBASE=/usr/src/lib

# PYTHONUNBUFFERED: Force stdin, stdout and stderr to be totally unbuffered. (equivalent to `python -u`)
# PYTHONHASHSEED: Enable hash randomization (equivalent to `python -R`)
# PYTHONDONTWRITEBYTECODE: Do not write byte files to disk, since we maintain it as readonly. (equivalent to `python -B`)
ENV PYTHONUNBUFFERED=1 \
    PYTHONHASHSEED=random \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUSERBASE=$PYTHONUSERBASE \
    PATH="${PYTHONUSERBASE}/bin:${PATH}"

# Setup PYTHONUSERBASE directory
# we allow running / managing these folders by non-root users. Thus need chmod
RUN set -ex; \
    mkdir -p $PYTHONUSERBASE && chmod 777 ${PYTHONUSERBASE}; \
    mkdir -p $WORKDIR && chmod 777 ${WORKDIR}

COPY python/requirements.txt python/requirements-tests.txt ./
RUN pip install \
    -r requirements.txt \
    -r requirements-tests.txt
